python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_1.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_2.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_3.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_4.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_5.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_6.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_7.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_8.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_9.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_10.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_11.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_12.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_13.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_14.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_15.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_16.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_17.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_18.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_19.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_20.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_21.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_22.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_23.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_24.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_25.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_26.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_27.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_28.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_29.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_30.fa 1000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_1.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_2.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_3.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_4.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_5.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_6.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_7.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_8.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_9.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_10.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_11.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_12.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_13.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_14.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_15.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_16.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_17.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_18.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_19.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_20.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_21.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_22.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_23.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_24.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_25.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_26.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_27.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_28.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_29.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_30.fa 10000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_1.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_2.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_3.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_4.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_5.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_6.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_7.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_8.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_9.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_10.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_11.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_12.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_13.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_14.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_15.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_16.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_17.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_18.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_19.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_20.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_21.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_22.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_23.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_24.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_25.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_26.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_27.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_28.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_29.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_30.fa 100000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_1.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_2.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_3.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_4.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_5.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_6.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_7.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_8.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_9.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_10.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_11.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_12.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_13.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_14.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_15.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_16.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_17.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_18.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_19.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_20.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_21.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_22.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_23.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_24.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_25.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_26.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_27.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_28.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_29.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_30.fa 1000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_1.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_2.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_3.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_4.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_5.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_6.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_7.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_8.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_9.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_10.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_11.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_12.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_13.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_14.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_15.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_16.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_17.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_18.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_19.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_20.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_21.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_22.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_23.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_24.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_25.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_26.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_27.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_28.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_29.fa 10000000
python src/simulate_aln.py ../therm_constraints_rate_variation/ddG_calculations/foldX/foldx_ddG/132L_A_foldx_ddG.txt trees/n2_bl0.4.tre aln/test_site_dupl/n2_bl0.4_30.fa 10000000
